language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
install:
  - yarn
script:
  - yarn format-check
  - yarn lint
  - yarn type-check
  - yarn build
branches:
  only:
    - master
    - /^v\d+\.\d+.*$/
